services:
  postgres:
    image: postgres:16 # Use a specific version tag, e.g., postgres:16
    container_name: bitblik_postgres_db
    environment:
      POSTGRES_USER: user # Replace with your desired username
      POSTGRES_PASSWORD: password # Replace with a strong password
      POSTGRES_DB: bitblik_db # Replace with your desired database name
    ports:
      - "5434:5432" # Map container port 5432 to host port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data

  coordinator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coordinator
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
    environment:
      MAKER_FEE: 0.25
      TAKER_FEE: 0.75
      RESERVATION_SECONDS: 30
      SIMPLEX_GROUP: 'Bitblik-test'
      LND_HOST: localhost
      DB_HOST: postgres
      DB_USER: user
      DB_PORT: 5432
      DB_PASSWORD: password
      DB: bitblik_db
    volumes:
      - ./tls.cert:/app/tls.cert:ro
      - ./admin.macaroon:/app/admin.macaroon:ro
    ports:
      - "8686:8080"

  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    container_name: bitblik_client
    ports:
      - "8787:80"  # Default Vite port
#    depends_on:
#      - coordinator

volumes:
  postgres_data: # Define the named volume

