-- Script to initialize the database schema for the BitBlik Coordinator

-- Create the offers table
CREATE TABLE IF NOT EXISTS offers (
  id UUID PRIMARY KEY,
  amount_sats BIGINT NOT NULL,
  maker_fees BIGINT NOT NULL, -- Renamed from fee_sats
  maker_pubkey TEXT NOT NULL,
  taker_pubkey TEXT,
  taker_lightning_address TEXT, -- Added for LNURL payout
  taker_invoice TEXT, -- Added to store resolved invoice before payment attempt
  blik_code TEXT,
  hold_invoice_payment_hash TEXT UNIQUE NOT NULL,
  hold_invoice_preimage TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  reserved_at TIMESTAMPTZ,
  blik_received_at TIMESTAMPTZ,
  maker_confirmed_at TIMESTAMPTZ,
  settled_at TIMESTAMPTZ,
  taker_paid_at TIMESTAMPTZ,
  taker_fees BIGINT NULL -- Renamed from taker_fees_sats
);

-- Add index for faster lookups by status
CREATE INDEX IF NOT EXISTS idx_offers_status ON offers (status);

-- Optional: Add other indexes based on query patterns
CREATE INDEX IF NOT EXISTS idx_offers_maker_pubkey ON offers (maker_pubkey);
CREATE INDEX IF NOT EXISTS idx_offers_taker_pubkey ON offers (taker_pubkey);

-- Grant necessary privileges (adjust user 'user' if needed)
-- GRANT ALL PRIVILEGES ON TABLE offers TO "user";
-- GRANT USAGE, SELECT ON SEQUENCE offers_id_seq TO "user"; -- If using SERIAL instead of UUID

-- Note: The DatabaseService code uses UUIDs generated by the application.
-- If you prefer auto-incrementing IDs, change 'id UUID PRIMARY KEY' to
-- 'id SERIAL PRIMARY KEY'.
